[package]
name = "demo"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
cxx = "1.0"
serde = "1.0.132"
rmp-serde = "0.15.5"
lazy_static = "1.4.0"
rkyv = "0.7.26"

[build-dependencies]
cxx-build = "1.0"
