[package]
name = "ray-rs"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
serde = "1.0.132"
rmp-serde = "0.15.5"
lazy_static = "1.4.0"
rkyv = "0.7.26"
uniffi = "0.16.0"
