[package]
name = "demo"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
