[package]
name = "simple"
version = "0.0.0"
authors = ["Jonathan Chuang"]
license = "Apache-2.0"
edition = "2018"
publish = true

[dependencies]
ray-rs = "0.0.0" # { path="../../ray-rs" }

[lib]
crate-type = ["rlib", "cdylib"]
